' SPDX-License-Identifier: MPL-2.0

' Legacy console runner kept during the MSTest migration parity check (V13-3);
' deleted once dotnet test reports the same 82 results (spec 05 section 4 steps 5-6).
Module Program
    Private _failures As Integer

    Sub Main()
        Dim parsing = New ParsingTests()
        Dim gridModel = New GridModelTests()
        Dim fileSafety = New FileSafetyTests()
        Dim schema = New SchemaValidationTests()
        Dim security = New SecurityGuardTests()
        Dim conversion = New ConversionTests()
        Dim editorState = New EditorStateTests()
        Dim settingsEnc = New SettingsEncodingTests()
        Dim tableModel = New TableModelTests()

        Run("Parse standard JSON to tree", AddressOf parsing.ParseStandardJsonToTree)
        Run("Attach source line and column to nodes", AddressOf parsing.AttachSourceLineAndColumnToNodes)
        Run("Infer primitive values and serialize grid", AddressOf gridModel.InferPrimitiveValuesAndSerializeGrid)
        Run("Infer primitive values by MVP-0 rules", AddressOf gridModel.InferPrimitiveValuesByMvp0Rules)
        Run("Serialize edited grid key", AddressOf gridModel.SerializeEditedGridKey)
        Run("Parse JSONC with comments and trailing commas", AddressOf parsing.ParseJsonCWithCommentsAndTrailingCommas)
        Run("Parse representative JSON5 syntax", AddressOf parsing.ParseRepresentativeJson5Syntax)
        Run("Parse JSON Lines as array tree", AddressOf parsing.ParseJsonLinesAsArrayTree)
        Run("Grid actions add delete move and change type", AddressOf gridModel.GridActionsAddDeleteMoveAndChangeType)
        Run("Grid undo restores moved node order", AddressOf gridModel.GridUndoRestoresMovedNodeOrder)
        Run("Grid filter keeps matching nodes and parents", AddressOf gridModel.GridFilterKeepsMatchingNodesAndParents)
        Run("Report syntax errors with location", AddressOf parsing.ReportSyntaxErrorsWithLocation)
        Run("Save creates backup and keeps valid JSON", AddressOf fileSafety.SaveCreatesBackupAndKeepsValidJson)
        Run("Invalid save preserves existing file", AddressOf fileSafety.InvalidSavePreservesExistingFile)
        Run("Recovery snapshots can be listed and loaded", AddressOf fileSafety.RecoverySnapshotsCanBeListedAndLoaded)
        Run("Diagnostics report omits JSON body", AddressOf fileSafety.DiagnosticsReportOmitsJsonBody)
        Run("Parse 10MB target JSON within practical bounds", AddressOf parsing.Parse10MbTargetJsonWithinPracticalBounds)
        Run("Nodes carry RFC6901 JSON Pointers", AddressOf parsing.NodesCarryJsonPointers)
        Run("Grid value edit snapshot becomes one undo operation", AddressOf gridModel.GridValueEditSnapshotBecomesOneUndoOperation)
        Run("Diagnostics report omits diagnostic and exception messages", AddressOf fileSafety.DiagnosticsReportOmitsMessages)
        Run("UT-M2-001 schema required error", AddressOf schema.SchemaRequiredError)
        Run("UT-M2-002 schema type error with body position", AddressOf schema.SchemaTypeErrorWithBodyPosition)
        Run("UT-M2-003 schema pattern error", AddressOf schema.SchemaPatternError)
        Run("Schema enum range additionalProperties and items", AddressOf schema.SchemaEnumRangeAdditionalAndItems)
        Run("UT-M2-004 HTTP schema URL is blocked", AddressOf security.HttpSchemaUrlIsBlocked)
        Run("UT-M2-005 dangerous schema redirects are blocked", AddressOf security.DangerousSchemaRedirectsAreBlocked)
        Run("DNS-resolved private and mapped addresses are blocked", AddressOf security.DnsResolvedPrivateAddressesAreBlocked)
        Run("IT-M2-001 schema diagnostics map to body location", AddressOf schema.SchemaDiagnosticsMapToBodyLocation)
        Run("UT-M3-001 JSON to XML with attributes", AddressOf conversion.JsonToXmlWithAttributes)
        Run("UT-M3-002 JSON to YAML two space list", AddressOf conversion.JsonToYamlTwoSpaceList)
        Run("UT-M3-003 XXE is not resolved", AddressOf conversion.XxeIsNotResolved)
        Run("IT-M3-001 failed conversion never touches files", AddressOf conversion.FailedConversionNeverTouchesFiles)
        Run("XML to JSON round trip", AddressOf conversion.XmlToJsonRoundTrip)
        Run("YAML to JSON round trip", AddressOf conversion.YamlToJsonRoundTrip)
        Run("YAML unsupported features are rejected", AddressOf conversion.YamlUnsupportedFeaturesAreRejected)
        Run("Text export creates backup and preserves target on failure", AddressOf fileSafety.TextExportCreatesBackupAndPreservesTarget)
        Run("UT-P2-STA-001 capture restore keeps selected and expanded pointers", AddressOf editorState.P2StateCaptureRestoreKeepsPointers)
        Run("UT-P2-STA-002 missing pointer falls back to nearest ancestor", AddressOf editorState.P2MissingPointerFallsBackToAncestor)
        Run("UT-P2-STA-003 offset maps to key value and delimiter nodes", AddressOf editorState.P2OffsetMapsToNode)
        Run("UT-P2-STA-004 pointer display uses root label", AddressOf editorState.P2PointerDisplayUsesRootLabel)
        Run("UT-P2-STA-005 state stores text caret and scroll offsets", AddressOf editorState.P2StateStoresTextOffsets)
        Run("UT-P2-STA-006 10MB formatted offset lookup stays within 200ms", AddressOf editorState.P2TenMbFormattedOffsetLookupWithin200Ms)
        Run("UT-P2-FLD-001 folding ignores braces in strings and handles nesting", AddressOf editorState.P2FoldingIgnoresStringBracesAndNests)
        Run("UT-P2-FLD-002 single line blocks are not foldable", AddressOf editorState.P2SingleLineBlocksAreNotFoldable)
        Run("UT-P2-RPL-001 replace all supports case and regex options", AddressOf editorState.P2ReplaceAllSupportsCaseAndRegex)
        Run("UT-P2-GRD-001 Redo restores moved node order", AddressOf gridModel.P2GridRedoRestoresMovedNodeOrder)
        Run("UT-P2-GRD-002 New grid operation clears Redo", AddressOf gridModel.P2GridRedoClearedByNewOperation)
        Run("UT-P2-GRD-003 Duplicate creates unique sibling", AddressOf gridModel.P2GridDuplicateCreatesUniqueSibling)
        Run("UT-P2-SET-001 settings round trip", AddressOf settingsEnc.P2SettingsRoundTrip)
        Run("UT-P2-SET-002 broken settings are moved aside", AddressOf settingsEnc.P2BrokenSettingsMovedAside)
        Run("UT-P2-SET-003 unknown settings keys are preserved", AddressOf settingsEnc.P2UnknownSettingsKeysPreserved)
        Run("UT-P2-SET-004 recent files max duplicate clear", AddressOf settingsEnc.P2RecentFilesMaxDuplicateClear)
        Run("UT-P2-ENC-001 encoding samples are detected", AddressOf settingsEnc.P2EncodingSamplesDetected)
        Run("UT-P2-ENC-002 save preserves detected encoding", AddressOf settingsEnc.P2SavePreservesDetectedEncoding)
        Run("UT-P2-ENC-003 newline majority is preserved", AddressOf settingsEnc.P2NewLineMajorityDetected)
        Run("UT-P2-ENC-004 undecodable bytes fall back to UTF-8 warning", AddressOf settingsEnc.P2EncodingFallbackWarning)
        Run("UT-P2-FMT-001 format sniffer detects JSONC JSON5 JSONL", AddressOf parsing.P2FormatSnifferDetectsVariants)
        Run("UT-P2-FMT-002 unknown format is not confident", AddressOf parsing.P2FormatSnifferUnknownIsNotConfident)
        Run("File log omits exception messages and body", AddressOf fileSafety.P2FileLogOmitsBody)
        Run("UT-P2-SCH-001 const mismatch reports SCH-CONST", AddressOf schema.P2SchemaConstMismatch)
        Run("UT-P2-SCH-002 string length violations report min and max codes", AddressOf schema.P2SchemaStringLength)
        Run("UT-P2-SCH-003 local ref delegates to definitions", AddressOf schema.P2SchemaLocalRef)
        Run("UT-P2-SCH-004 ref cycle stops without recursion", AddressOf schema.P2SchemaRefCycle)
        Run("UT-P2-SCH-005 external ref warns without network access", AddressOf schema.P2SchemaExternalRefWarning)
        Run("UT-P2-SCH-006 format violations warn", AddressOf schema.P2SchemaFormatWarnings)
        Run("UT-P2-CNV-001 RepeatParentName expands arrays with the property name", AddressOf conversion.P2XmlRepeatParentName)
        Run("UT-P2-CNV-002 XsiNil writes nil attribute and xsi namespace", AddressOf conversion.P2XmlXsiNil)
        Run("UT-P2-CNV-003 default XML options match the legacy output", AddressOf conversion.P2XmlDefaultOptionsRegression)
        Run("UT-P2-CNV-004 JSONL save writes one parsable line per element", AddressOf conversion.P2JsonLinesArrayRoot)
        Run("UT-P2-CNV-005 JSONL save of non-array root warns", AddressOf conversion.P2JsonLinesNonArrayRoot)
        Run("UT-P2-CNV-006 JSONL round trip preserves structure", AddressOf conversion.P2JsonLinesRoundTrip)
        Run("UT-P2-CMP-001 completion candidates merge siblings and schema minus existing", AddressOf editorState.P2CompletionCandidates)
        Run("UT-P2-GRD-004 cross-parent move allows confirms and rejects", AddressOf gridModel.P2GridCrossParentMove)
        Run("UT-P2-GRD-005 empty braces and brackets infer container types", AddressOf gridModel.P2GridInferContainerTypes)
        Run("UT-P2-TBL-001 table columns are first-seen union with empty missing cells", AddressOf tableModel.P2TableColumnsUnionWithMissingCells)
        Run("UT-P2-TBL-002 non-object elements land in the value column", AddressOf tableModel.P2TableNonObjectElementsUseValueColumn)
        Run("UT-P2-TBL-003 missing cell edit materializes the property on that row only", AddressOf tableModel.P2TableMissingCellEditMaterializesRowOnly)
        Run("UT-P2-TBL-004 cell edit infers type and undoes as one operation", AddressOf tableModel.P2TableCellEditInfersTypeAndUndoes)
        Run("UT-P2-TBL-005 display sort leaves array children order unchanged", AddressOf tableModel.P2TableDisplaySortLeavesStructure)
        Run("UT-P2-TBL-006 apply sort rewrites array order and undoes as one operation", AddressOf tableModel.P2TableApplySortRewritesStructure)
        Run("UT-P2-TBL-007 10001 rows exceed the table limit", AddressOf tableModel.P2TableRowLimitExceeded)
        Run("UT-P2-TBL-008 10000 rows build within two seconds", AddressOf tableModel.P2TableTenThousandRowsBuildFast)

        If _failures > 0 Then
            Console.Error.WriteLine($"{_failures} test(s) failed.")
            Environment.ExitCode = 1
            Return
        End If

        Console.WriteLine("All tests passed.")
    End Sub

    Private Sub Run(name As String, test As Action)
        Try
            test()
            Console.WriteLine($"PASS {name}")
        Catch ex As Exception
            _failures += 1
            Console.Error.WriteLine($"FAIL {name}: {ex.Message}")
        End Try
    End Sub
End Module
